### ISSUE TITLE
Add "deployed by..." to Deployment Configuration

### ISSUE THREAD

**Issue by benjamingregory** [astronomerio/orbit-ui#29]
In the configuration of each deployment, the latest deployment time is shown. As a user, I would like to see who deployed at this time.

![screen shot 2018-07-10 at 1 01 04 pm](https://user-images.githubusercontent.com/8160412/42531553-7920fa20-8441-11e8-9b5e-0af58e54092d.png)

**Comment by pcmaffey** [comment]
Gonna close this because its part of Activity/Audit Logs feature that's already on roadmap. If we feel we need a temp solution in the meantime, can reopen and build in specific log for `createdBy`.

**Comment by benjamingregory** [comment]
@pcmaffey Sounds good - just made it off the top of my head when I saw it.
