### ISSUE TITLE
React-loadable causing error page (fixed on refresh)

### ISSUE THREAD

**Issue by pcmaffey** [astronomerio/orbit-ui#44]
- Only happening on prod, either because of network latency issues or prod webpack build

**Comment by pcmaffey** [comment]
https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]=

**Comment by paolaperaza** [comment]
@pcmaffey I'm finding that the first time I click into https://app.astronomer.cloud/ from a new/different browser, I get the "DAG Gone it" page until I do a refresh. A few customers are seeing something similar - assuming that's related to this issue, if not the same?

**Comment by pcmaffey** [comment]
https://github.com/jamiebuilds/react-loadable/pull/110#issuecomment-371013933

**Comment by pcmaffey** [comment]
Possible fix, will need testing on prod where it seems the error only occurs
