### ISSUE TITLE
Text next to bullet-checkmarks missing on /signup

### ISSUE THREAD

**Issue by ryw** [astronomerio/orbit-ui#51]
looks like `color: transparent;` is set

**Comment by pcmaffey** [comment]
Hmm, I can't reproduce - they're there for me on app.datarouter.ai. But I do hide some stuff at different resolutions... can you send me your browser window width x height?

**Comment by ryw** [comment]
I can see the `WHY WE LOVE CLICKSTREAM` on https://www.astronomer.io/clickstream/

Here's what app.datarouter.ai looks like:
<img width="1354" alt="screen shot 2018-09-28 at 9 01 45 am" src="https://user-images.githubusercontent.com/4283/46209918-36ff1000-c2fd-11e8-91c0-3b235c06d107.png">
