### ISSUE TITLE
Corner Image becomes square when cursor is moved over it

### ISSUE THREAD

**Issue by benjamingregory** [astronomerio/orbit-ui#53]
Browser: Safari
Version: 12.0

Unclear if this is intentional but it was unexpected when I moved my cursor over it.

![ezgif-1-b72e57ed66f9](https://user-images.githubusercontent.com/8160412/47173961-a6e53280-d2cc-11e8-9484-25d1c7350ac1.gif)

**Comment by pcmaffey** [comment]
can't duplicate on normal safari...

**Comment by benjamingregory** [comment]
![](https://media.giphy.com/media/Ou18ZgE49Fss0/giphy.gif)
