### ISSUE TITLE
Signing up via Google and Github produce separate namespaces

### ISSUE THREAD

**Issue by benjamingregory** [astronomerio/orbit-ui#54]
Depending on the sign up method, the name shown will be different.
Browser: Safari
Version: 12.0

![ezgif-1-7408cf735038](https://user-images.githubusercontent.com/8160412/47174334-8bc6f280-d2cd-11e8-9553-3c22715cf4c9.gif)

**Comment by pcmaffey** [comment]
When you go to Personal Settings, what name shows in the field for each?

**Comment by benjamingregory** [comment]
When Google it's `Ben Gregory`.
When Github it's `Ben`.

**Comment by pcmaffey** [comment]
So it's showing different names because you have different names set with each service. We just use your profile data from the service logged in with as source of truth.
